import React, { useState } from 'react';
import { Play, X, ExternalLink, Code2, ChevronLeft, ChevronRight, FileText } from 'lucide-react';

interface ProjectVideo {
  label: string;
  src: string;
}

interface Project {
  title: string;
  description: string;
  documentation: string;
  tech: string[];
  videos?: ProjectVideo[];
  color: string;
}

const ProjectsWindow: React.FC = () => {
  const [activeProject, setActiveProject] = useState<Project | null>(null);
  const [currentVideoIndex, setCurrentVideoIndex] = useState(0);
  const [docProject, setDocProject] = useState<Project | null>(null);

  const projects: Project[] = [
   {
      title: 'Full-stack web app for JVM static analysis and real-time monitoring',
      description: 'JVM metadata extraction and real-time monitoring dashboards (CPU, memory, GC)',
            documentation: 'Private Web Application\n Technologies used: Spring Boot, Thymeleaf, Oracle.\n Full documentation and source code are restricted due to privacy reasons.',

      tech: ['Spring Boot', 'Oracle', 'Thymeleaf'],
      videos: [
        { label: 'real-time JVM monitoring', src: '/jmv runing demo.mp4' },
        { label: 'Static Analysis', src: '/demo application-static prj.mp4' }
      ],
      color: 'from-violet-500 to-purple-500',
    },
    {
      title: 'Mobile passport scanning With OCR integration Internship Project',
      description: 'Hybrid mobile application development for passport scanning & OCR integration',
documentation: `
### 4. Implemented Solution (System Implementation)

The developed solution is a hybrid mobile application that enables users to scan their passports directly using their smartphones and automatically extract personal information from the Machine Readable Zone (MRZ).

The application was built using the Ionic framework combined with Angular, providing a modern user interface while leveraging native smartphone capabilities.

#### 4.1 Passport Image Capture
The first page of the passport is captured using the smartphone camera through Capacitor Camera. The captured image is temporarily stored on the client side in order to be processed by the OCR module.

#### 4.2 OCR and Text Extraction
An OCR engine integrated into the front-end converts the captured passport image into raw text. This step represents the foundation of the MRZ data processing pipeline.

---

### 4.3 MRZ Code Processing

The text generated by the OCR engine is analyzed to extract only the last two lines of the passport, which correspond to the Machine Readable Zone (MRZ).

A dedicated TypeScript function performs the following operations:
- Identification and extraction of MRZ lines from OCR output
- Parsing of MRZ strings using the '<' separator character
- Interpretation of data fields according to ICAO MRZ standards
- Extraction of the passport holder’s personal information

The extracted data includes:
- First name and last name
- Passport number
- Nationality
- Date of birth
- Gender
- Passport expiration date

These values are automatically formatted and populated into a structured client form, ready to be transmitted to the backend.

---

### 4.4 Backend Communication

Once the MRZ data is structured, the mobile application communicates with the backend through RESTful Web Services developed using Spring Boot.

Two dedicated services were implemented:
- A service for transmitting and persisting personal identification data
- A service for uploading and storing the passport image

---

### 5. Technical Architecture

| Layer | Technology | Role |
|------|-----------|------|
| Mobile Application | Ionic + Angular | User interface and access to native mobile features |
| OCR & MRZ Parsing | Angular / TypeScript | Text extraction and MRZ data interpretation |
| Backend Services | Spring Boot | REST API exposure and business logic |
| Database | Oracle | Secure storage of client data |
| Communication | REST API | Data exchange between mobile app and backend |

---

### 6. Achieved Results

- Significant reduction in manual data entry
- Improved accuracy and reliability of collected information
- Increased user autonomy
- Seamless integration with an existing information system
- Elimination of dependency on physical passport scanners

---

### 7. Confidentiality

This project was carried out in a professional and confidential context.  
Advanced technical details, source code, and real data cannot be disclosed publicly.
`


,
      tech: ['Spring Boot', 'Ionic', 'Oracle', 'Angular'],
      videos: [{ label: 'Demo client features', src: '/media1.mp4' },{ label: 'Demo admin dashboard', src: '/media2.mp4' }],
      color: 'from-violet-500 to-purple-500',
    },
    {
      title: 'Automated Resume Screening System',
      description: 'CV analysis & candidate shortlisting application with intelligent parsing and scoring algorithms',
        documentation: `
### 4. Implemented Solution

This project is an AI-assisted resume screening and candidate shortlisting system designed to automate basic evaluation of resumes against job descriptions.

The application is built with **NestJS** for the backend, **TypeORM** for database handling, and uses **Hugging Face** models to compute similarity scores between candidate resumes and job requirements. Resumes are uploaded as PDF files, parsed, and analyzed to generate a relevance score.

#### 4.1 Resume Upload and Parsing
Candidates submit their CVs through the web interface. PDF files are parsed using a simple text extraction library to retrieve the content for analysis.

#### 4.2 AI Scoring
The extracted text is compared with the job description using a Hugging Face AI model. A numeric score is generated to indicate how closely the candidate matches the job requirements.

#### 4.3 Candidate Shortlisting
Candidates with scores above a defined threshold are highlighted as potential matches. HR users can view and validate applications, updating the status to accepted or rejected.  

#### 4.4 Notifications
Upon validation, the system can send an automated email to notify the candidate about the outcome.

---

### 5. Technical Architecture

| Layer | Technology | Role |
|-------|-----------|------|
| Backend | NestJS + TypeORM | Handles business logic and API endpoints |
| AI Scoring | Hugging Face API | Compares CVs to job descriptions |
| Resume Parsing | pdf-parse | Extracts text from uploaded PDFs |
| Notifications | MailService | Sends emails to candidates |
| Database | PostgreSQL | Stores candidates, job offers, scores, and status |
| Frontend | Angular | Candidate submission and HR dashboard |

---

### 6. Workflow

1. Candidate submits CV.
2. System parses PDF and extracts text.
3. AI model generates a score based on job description.
4. Shortlist is created for HR review.
5. HR validates or rejects candidates.
6. Candidate receives notification email.

---

### 7. Outcomes

- Faster and automated resume screening.
- Candidates scored according to job relevance.
- Simple dashboard for HR to review and validate applications.
- Academic-level demonstration of AI-assisted recruitment workflow.
`,

      tech: ['NestJS', 'Angular', 'TypeScript'],
      videos: [
        { label: 'Full Demo', src: '/Automated-Resume-Screening-Candidate-Shortlisting-Web-App demo.mp4' },
        
      ],
      color: 'from-primary to-accent',
    },
     {
      title: 'HR & Leave Management System',
      description: 'Employee management with authentication, notifications, and approval workflows',
documentation: `
### 4. Implemented Solution

This project is a web-based workforce management system designed to manage employee leave, timesheets, performance evaluations, and HR operations in a centralized platform.

The application is developed using **NestJS** for the backend and **Angular** for the frontend. It supports role-based access for employees and HR administrators, ensuring secure and structured management of organizational data.

#### 4.1 Authentication and Roles
The system uses JWT-based authentication to secure user access. Users are assigned roles such as Employee, HR, or Admin, which define their permissions and accessible features.

#### 4.2 Leave Management
Employees can submit leave requests and view their remaining leave balance. HR administrators can review, approve, or reject leave requests through an administrative dashboard.

#### 4.3 Timesheet Management
Employees record their daily working hours using timesheets. HR users validate submitted timesheets to ensure accurate tracking of working time.

#### 4.4 Performance Evaluations
HR administrators can create and manage employee performance evaluations. Employees are able to consult their evaluation results through their personal space.

#### 4.5 Notifications
The system provides notifications for important events such as leave approval or rejection, timesheet validation, and evaluation updates.

---

### 5. Technical Architecture

| Layer | Technology | Role |
|-------|-----------|------|
| Frontend | Angular | User interface for employees and HR |
| Backend | NestJS | Business logic and REST APIs |
| Authentication | Passport.js + JWT | Secure access and role control |
| Database | MySQL + TypeORM | Data persistence |
| File Upload | Multer | Upload of leave-related documents |
| Notifications | Cron / Background Jobs | Automated alerts and reminders |

---

### 6. Workflow

1. User logs into the system.
2. Employee submits leave requests or timesheets.
3. HR reviews and validates submissions.
4. System updates request status.
5. Notifications are sent to users.
6. HR consults reports and statistics.

---

### 7. Outcomes

- Centralized employee and HR management.
- Efficient leave and timesheet processing.
- Secure role-based access control.
- Improved communication through notifications.
- Academic-level implementation of a workforce management system.
`,
      tech: ['NestJS', 'Angular', 'PostgreSQL'],
          videos: [{ label: 'Employee Leave Request & Timesheet Submission', src: '/employee1.mp4' },{ label: 'HR Validation of Employee Requests', src: '/rh.mp4' },{ label: 'View HR Decision Notifications', src: '/employee2.mp4' }],

      color: 'from-emerald-500 to-teal-500',
    },
    {
      title: 'Hotel Reservation Management System',
      description: 'Complete hotel booking and management platform with real-time availability tracking',
            documentation: 'A comprehensive hotel management platform designed to streamline booking operations and enhance guest experiences. The system provides real-time room availability tracking, reservation management, and booking confirmations. Key features include dynamic pricing, room type management, guest profile handling, and detailed reporting. Developed using Spring Boot for enterprise-grade backend services, Thymeleaf for server-side rendered views, and Oracle database for reliable transaction management.',

      tech: ['Spring Boot', 'Thymeleaf', 'Oracle'],
      videos: [
        { label: 'Demo', src: '/hotel-demo.mp4' }
      ],
      color: 'from-amber-500 to-orange-500',
    },
    {
      title: 'Movie Playlist & Recommendation App',
      description: 'Personal movie tracker with smart recommendations powered by TMDB API integration',
            documentation: 'A comprehensive hotel management platform designed to streamline booking operations and enhance guest experiences. The system provides real-time room availability tracking, reservation management, and booking confirmations. Key features include dynamic pricing, room type management, guest profile handling, and detailed reporting. Developed using Spring Boot for enterprise-grade backend services, Thymeleaf for server-side rendered views, and Oracle database for reliable transaction management.',

      tech: ['Ionic', 'React', 'Firebase', 'TMDB API'],
      videos: [
        { label: 'Demo', src: '/movzie-app-demo.mp4' }
      ],
      color: 'from-violet-500 to-purple-500',
    },
 
  
   
  ];


  const openDemo = (project: Project) => {
    setActiveProject(project);
    setCurrentVideoIndex(0);
  };

  const closeModal = () => {
    setActiveProject(null);
    setCurrentVideoIndex(0);
  };

  const nextVideo = () => {
    if (activeProject?.videos && currentVideoIndex < activeProject.videos.length - 1) {
      setCurrentVideoIndex(prev => prev + 1);
    }
  };

  const prevVideo = () => {
    if (currentVideoIndex > 0) {
      setCurrentVideoIndex(prev => prev - 1);
    }
  };

  const hasVideos = (project: Project) => project.videos && project.videos.length > 0;

  return (
    <div className="p-6 relative">
      <h2 className="text-xl font-bold section-title mb-6 flex items-center gap-3">
        <Code2 size={24} className="text-primary" />
        My Projects
      </h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {projects.map((project, index) => (
          <div
            key={index}
            className="glass-card p-5 group relative overflow-hidden"
          >
            {/* Gradient accent bar */}
            <div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${project.color}`} />
            
            <div className="flex items-start justify-between mb-3">
              <h3 className="font-semibold text-foreground text-sm leading-tight pr-2">
                {project.title}
              </h3>
              {hasVideos(project) && (
                <button 
                  onClick={() => openDemo(project)}
                  className="flex-shrink-0 p-2 bg-primary/20 rounded-full hover:bg-primary/30 transition-all group-hover:scale-110"
                >
                  <Play size={14} className="text-primary" fill="currentColor" />
                </button>
              )}
            </div>
            
            <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
              {project.description}
            </p>
            
            <div className="flex flex-wrap gap-2">
              {project.tech.map((t) => (
                <span key={t} className="skill-badge text-[10px]">
                  {t}
                </span>
              ))}
            </div>

            {/* Action Buttons */}
            <div className="mt-4 flex gap-2">
              {hasVideos(project) && (
                <button
                  onClick={() => openDemo(project)}
                  className="flex-1 py-2 px-3 bg-gradient-to-r from-primary/20 to-accent/20 rounded-lg text-xs font-medium text-foreground hover:from-primary/30 hover:to-accent/30 transition-all flex items-center justify-center gap-2 border border-primary/20"
                >
                  <Play size={12} className="text-primary" />
                  Demo {project.videos && project.videos.length > 1 && `(${project.videos.length})`}
                </button>
              )}
              <button
                onClick={() => setDocProject(project)}
                className="flex-1 py-2 px-3 bg-gradient-to-r from-blue-500/20 to-cyan-500/20 rounded-lg text-xs font-medium text-foreground hover:from-blue-500/30 hover:to-cyan-500/30 transition-all flex items-center justify-center gap-2 border border-blue-500/20"
              >
                <FileText size={12} className="text-blue-400" />
                Documentation
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Video Modal */}
      {activeProject && hasVideos(activeProject) && (
        <div className="fixed inset-0 video-modal-overlay flex items-center justify-center z-50">
          <div className="gradient-border max-w-4xl w-full mx-4">
            <div className="bg-card rounded-xl overflow-hidden">
              <div className="flex justify-between items-center p-4 border-b border-border">
                <div>
                  <h3 className="font-semibold text-foreground">{activeProject.title}</h3>
                  <p className="text-xs text-muted-foreground">
                    {activeProject.videos && activeProject.videos.length > 1 
                      ? `${activeProject.videos[currentVideoIndex].label} (${currentVideoIndex + 1}/${activeProject.videos.length})`
                      : 'Project Demo'
                    }
                  </p>
                </div>
                <button
                  onClick={closeModal}
                  className="p-2 hover:bg-destructive/20 rounded-lg transition-colors"
                >
                  <X size={20} className="text-muted-foreground" />
                </button>
              </div>
              
              {/* Video Player */}
              <div className="relative bg-background">
                <video 
                  key={activeProject.videos![currentVideoIndex].src}
                  className="w-full aspect-video"
                  controls
                  autoPlay
                >
                  <source src={activeProject.videos![currentVideoIndex].src} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>

                {/* Navigation Arrows for Multiple Videos */}
                {activeProject.videos && activeProject.videos.length > 1 && (
                  <>
                    <button
                      onClick={prevVideo}
                      disabled={currentVideoIndex === 0}
                      className={`absolute left-2 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border transition-all ${
                        currentVideoIndex === 0 ? 'opacity-30 cursor-not-allowed' : 'hover:bg-primary/20'
                      }`}
                    >
                      <ChevronLeft size={24} className="text-foreground" />
                    </button>
                    <button
                      onClick={nextVideo}
                      disabled={currentVideoIndex === activeProject.videos.length - 1}
                      className={`absolute right-2 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border transition-all ${
                        currentVideoIndex === activeProject.videos.length - 1 ? 'opacity-30 cursor-not-allowed' : 'hover:bg-primary/20'
                      }`}
                    >
                      <ChevronRight size={24} className="text-foreground" />
                    </button>
                  </>
                )}
              </div>

              {/* Video Thumbnails/Tabs for Multiple Videos */}
              {activeProject.videos && activeProject.videos.length > 1 && (
                <div className="p-4 border-t border-border flex gap-2 overflow-x-auto">
                  {activeProject.videos.map((video, idx) => (
                    <button
                      key={idx}
                      onClick={() => setCurrentVideoIndex(idx)}
                      className={`px-4 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${
                        idx === currentVideoIndex
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted text-muted-foreground hover:bg-muted/80'
                      }`}
                    >
                      {video.label}
                    </button>
                  ))}
                </div>
              )}

              {/* Tech Stack */}
              <div className="p-4 border-t border-border">
                <div className="flex flex-wrap justify-center gap-2">
                  {activeProject.tech.map((t) => (
                    <span key={t} className="skill-badge">
                      {t}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Documentation Modal */}
      {docProject && (
<div className="fixed inset-0 video-modal-overlay flex items-start justify-center z-50 pt-10">
          <div className="gradient-border max-w-2xl w-full mx-4">
            <div className="bg-card rounded-xl overflow-hidden">
              <div className="flex justify-between items-center p-4 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-lg bg-gradient-to-r ${docProject.color}`}>
                    <FileText size={18} className="text-white" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground text-sm">{docProject.title}</h3>
                    <p className="text-xs text-muted-foreground">Project Documentation</p>
                  </div>
                </div>
                <button
                  onClick={() => setDocProject(null)}
                  className="p-2 hover:bg-destructive/20 rounded-lg transition-colors"
                >
                  <X size={20} className="text-muted-foreground" />
                </button>
              </div>
              
         <div className="p-6 max-h-[60vh] overflow-y-auto">
  <div className="prose prose-sm max-w-none">
    <div className="text-muted-foreground leading-relaxed text-sm whitespace-pre-wrap">
      {docProject.documentation}
    </div>
  </div>

  <div className="mt-6 pt-4 border-t border-border">
    <h4 className="text-xs font-semibold text-foreground mb-3">
      Technologies Used
    </h4>
    <div className="flex flex-wrap gap-2">
      {docProject.tech.map((t) => (
        <span key={t} className="skill-badge">
          {t}
        </span>
      ))}
    </div>
  </div>
</div>

            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProjectsWindow;